name: "TODO: Run <linter-name> with reviewdog"
escription: "🐶 Run PMD analysis on your code and report results directly to pull request with the help of reviewdog."
author: "Dmitriy Belyaev"
inputs:
  github_token:
    description: "GITHUB_TOKEN"
    default: "${{ github.token }}"
  workdir:
    description: "Working directory relative to the root directory."
    default: "."
  ### Flags for reviewdog ###
  level:
    description: "Report level for reviewdog [info, warning, error]"
    default: "info"
  reporter:
    description: "Reporter of reviewdog command [github-pr-check, github-pr-review]."
    default: "github-pr-check"
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added, diff_context, file, nofilter].
      Default is added.
    default: "added"
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true, false]
      Default is `false`.
    default: "false"
  reviewdog_flags:
    description: "Additional reviewdog flags"
    default: ""
  ### Flags for PMD ###
  rulesets_path:
    description: "Path to the ruleset xml file."
    default: "rulesets/java/quickstart.xml"
runs:
  using: "docker"
  image: "Dockerfile"

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: "check"
  color: "blue"
